"""update incomes timestamps for consistency

Revision ID: 1ab48e699ae2
Revises: 8b0c01ec20b0
Create Date: 2025-08-19 21:33:26.654855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab48e699ae2'
down_revision: Union[str, Sequence[str], None] = '8b0c01ec20b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
