"""add notes to alert log

Revision ID: ac3b4f27f616
Revises: 14cb9782713f
Create Date: 2025-07-17 06:13:24.069067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3b4f27f616'
down_revision: Union[str, Sequence[str], None] = '14cb9782713f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_logs', 'period',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_logs', 'period',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
