"""Make period column not nullable

Revision ID: b97a26677e53
Revises: ac3b4f27f616
Create Date: 2025-07-17 06:22:50.910170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97a26677e53'
down_revision: Union[str, Sequence[str], None] = 'ac3b4f27f616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_logs', 'period',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_logs', 'period',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
