"""Make category and period fields non-nullable

Revision ID: f0a72d0184d8
Revises: 31d9cf4052d9
Create Date: 2025-07-17 00:54:47.618663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a72d0184d8'
down_revision: Union[str, Sequence[str], None] = '31d9cf4052d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budgets', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('budgets', 'period',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('budgets', 'period',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('budgets', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
