"""Updated budgets table

Revision ID: fe1e32665f45
Revises: 270c50987eed
Create Date: 2025-07-07 21:31:11.781982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1e32665f45'
down_revision: Union[str, Sequence[str], None] = '270c50987eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('limit', sa.Float(), nullable=False))
    op.add_column('budgets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('budgets', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('budgets', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('budgets', 'notes')
    op.drop_column('budgets', 'updated_at')
    op.drop_column('budgets', 'limit')
    # ### end Alembic commands ###
